CREATE TABLE CUSTOMER (
    CUST_ID INT PRIMARY KEY,
    CUST_FIRSTNAME VARCHAR(50) NOT NULL,
    CUST_LAST_NAME VARCHAR(50),
    CUST_BIRTHDATE DATE,
    CUST_GENDER CHAR(1) CHECK (CUST_GENDER IN ('1', '2')),
    CUST_ADDRESS VARCHAR(50),
    CUST_CITY VARCHAR(20),
    CUST_POSTCODE CHAR(5)
);

CREATE TABLE ACCOUNT (
    ACC_NUMBER CHAR(13) PRIMARY KEY,
    ACC_OWNER INT NOT NULL,
    ACC_DATE_CREATED DATE NOT NULL,
    ACC_BALANCE DECIMAL(10, 0),
    FOREIGN KEY (ACC_OWNER) REFERENCES CUSTOMER(CUST_ID)
);

CREATE TABLE TRANSACTION (
    TRS_ID BIGINT PRIMARY KEY,
    TRS_FROM_ACCOUNT CHAR(13) NOT NULL,
    TRS_DATE DATE NOT NULL,
    TRS_AMOUNT DECIMAL(10, 0) NOT NULL,
    TRS_TYPE CHAR(2) CHECK (TRS_TYPE IN ('DB', 'CR', 'TF')),
    FOREIGN KEY (TRS_FROM_ACCOUNT) REFERENCES ACCOUNT(ACC_NUMBER)
);

CREATE TABLE TRANSACTION_TRANSFER (
    TRS_ID BIGINT PRIMARY KEY,
    TRS_TO_TRANSACTION BIGINT NOT NULL,
    TRS_STATUS INT CHECK (TRS_STATUS IN (0, 1, -1)),
    FOREIGN KEY (TRS_TO_TRANSACTION) REFERENCES TRANSACTION(TRS_ID)
);


-- Recapitulation of number of accounts owned by every customer.--
SELECT ACC_OWNER, COUNT(ACC_NUMBER) AS NUM_ACCOUNTS
FROM ACCOUNT
GROUP BY ACC_OWNER;


--All transactions created by John Michael sorted by account number and--
transaction date
SELECT T.TRS_ID, T.TRS_FROM_ACCOUNT, T.TRS_DATE, T.TRS_AMOUNT, T.TRS_TYPE
FROM TRANSACTION T
JOIN ACCOUNT A ON T.TRS_FROM_ACCOUNT = A.ACC_NUMBER
JOIN CUSTOMER C ON A.ACC_OWNER = C.CUST_ID
WHERE C.CUST_FIRSTNAME = 'John' AND C.CUST_LAST_NAME = 'Michael'
ORDER BY T.TRS_FROM_ACCOUNT, T.TRS_DATE;

